services:
  db:
    build: ./db
    container_name: escola_db
    environment:
      POSTGRES_DB: escola
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "3001:5432"

  api:
    build:
      context: .
      dockerfile: dockerfile.app
    volumes:
      - .:/App
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: app:App
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: escola
      DB_USER: admin
      DB_PASSWORD: admin123
    depends_on:
      - db
    networks:
      - app_network

  prometheus:
    build:
      context: ./Observabilidade/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Observabilidade/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - app_network

  grafana:
    build:
      context: ./Observabilidade/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app_network

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:admin123@db:5432/escola?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  postgres_data:
  grafana_data: